name: Check Formatting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  format:
    name: PHP-CS-Fixer
    runs-on: ubuntu-26.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: ffi, mbstring
          ini-values: ffi.enable=true
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check code formatting
        run: composer run-script format:check
